### ISSUE TITLE
Selecting IDE

### ISSUE THREAD

**Issue by knoxxs** [knoxxs/numen#2]

**Comment by knoxxs** [comment]
Lets use https://www.jetbrains.com/webstorm/ . Bracket and sublime is not fast.

**Comment by knoxxs** [comment]
For license see the slack group

**Comment by knoxxs** [comment]
@vidzi close this issue if you are done

**Comment by vidzi** [comment]
Why did you choose Webstorm?
We have many other IDEs like:
1. Aptana
2. Dreamweaver
3. In Intellij also, we can plugins to support javascript debugging and all.

**Comment by knoxxs** [comment]
IMHO:
1. Aptana is over ecllipse and I hate ecllipse as it is too slow and buggy (compared to idea's products).
2. Dreamweaver is shit, I used for about two years it in college. Its good for `css` but not fast development and bad auto-completion (compared to idea's products)
3. Webstorm (an IDE designed by idea guys for web dev) vs plugin in Intellij idea (also designed by idea guys). I think its clear enough. Also intellij idea if for Java. It as many unwanted things like it does class search. There is no need for that in web dev.
